apiVersion: v1
kind: Service
metadata:
  name: app-arabic-service
  namespace: app-ns 
spec:
  selector:
    app: arabic-app
  ports:
  - name: arabic-srv-port
    protocol: TCP
    port: 80
    targetPort: 3000