apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins-ns
spec:
  type: NodePort
  selector:
    jenkins: CICD-1
  ports:
  - name: jenkins-srv-port
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30005
  - name: jnlp
    port: 50000
    targetPort: 50000
