---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-service-account
  namespace: jenkins-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-admin
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps", "batch"]      # Deployments, DaemonSets, Jobs, CronJobs
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin-binding
  namespace: jenkins-ns
subjects:
- kind: ServiceAccount
  name: jenkins-service-account 
  apiGroup: ""
  namespace: jenkins-ns
roleRef:
  kind: ClusterRole 
  name: jenkins-admin
  apiGroup: rbac.authorization.k8s.io
